language: emacs-lisp
env:
  matrix:
    - emacs=emacs

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq $emacs

script:
  - emacs --version
  - cd ~
  - git clone https://github.com/kimim/kimim-emacs
  - cp kimim-emacs/.emacs ~
  - mkdir .emacs.d
  - emacs --batch -l .emacs
